apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    k8s-app: elasticsearch
spec:
  type: ClusterIP
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200
---
kind: Endpoints
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    k8s-app: elasticsearch
subsets:
  - addresses:
    - ip: 192.168.218.53
    ports:
    - name: elasticsearch
      port: 9200
