apiVersion: v1
kind: Service
metadata:
  name: flb-metric
  namespace: logging
  labels:
    k8s-app: flb-metric
spec:
  type: ClusterIP
  selector:
    k8s-app: fluent-bit-logging
  ports:
  - name: fluentbit
    port: 2020
    targetPort: 2020
